# Generated by Django 4.2.30 on 2026-08-14 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        default="Passionate peer learner and mentor on SkillSwap AI.",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default="Gujarat, India", max_length=150
                    ),
                ),
                (
                    "skills_offered",
                    models.CharField(
                        blank=True,
                        default="Python, Django, Web Development",
                        max_length=300,
                    ),
                ),
                (
                    "skills_wanted",
                    models.CharField(
                        blank=True,
                        default="UI/UX Design, Machine Learning",
                        max_length=300,
                    ),
                ),
                ("xp", models.IntegerField(default=1500)),
                ("level", models.IntegerField(default=10)),
                ("rating", models.FloatField(default=4.9)),
                ("credits", models.IntegerField(default=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
