# Generated by Django 4.2.30 on 2026-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="availability",
            field=models.CharField(
                blank=True, default="Evenings & Weekends", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                    ("Expert", "Expert"),
                ],
                default="Intermediate",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="headline",
            field=models.CharField(
                blank=True, default="Peer Learner & Mentor", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="learning_mode",
            field=models.CharField(
                choices=[
                    ("1-on-1 Video", "1-on-1 Video"),
                    ("Async Chat", "Async Chat"),
                    ("Group Session", "Group Session"),
                    ("Flexible", "Flexible"),
                ],
                default="1-on-1 Video",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="website_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skills_offered",
            field=models.CharField(
                blank=True, default="Python, Django, Web Development", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="skills_wanted",
            field=models.CharField(
                blank=True, default="UI/UX Design, Machine Learning", max_length=500
            ),
        ),
    ]
