# Generated by Django 4.2.30 on 2026-08-14 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("exchanges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangerequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="exchangerequest",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exchangerequest",
            name="offered_skill",
            field=models.CharField(
                blank=True, default="Python Development", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="exchangerequest",
            name="requested_skill",
            field=models.CharField(blank=True, default="UI/UX Design", max_length=200),
        ),
        migrations.AddField(
            model_name="exchangerequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="exchangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
