# Generated by Django 4.2.30 on 2026-08-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchanges", "0002_exchangerequest_created_at_exchangerequest_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exchangerequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="exchangerequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exchangerequest",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="exchangerequest",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exchangerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
