# Generated by Django 4.2.30 on 2026-08-16 12:39

import certificates.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.CharField(
                        default=certificates.models.generate_cert_id,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("skill_title", models.CharField(max_length=200)),
                (
                    "achievement_title",
                    models.CharField(
                        default="Skill Mastery Certificate", max_length=200
                    ),
                ),
                ("issued_date", models.DateField(auto_now_add=True)),
                (
                    "issuer",
                    models.CharField(
                        default="SkillSwap AI Peer Learning Network", max_length=150
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Verified & Active"),
                            ("revoked", "Revoked"),
                            ("pending_approval", "Pending Admin Approval"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        default="Verified through peer exchange completion and mentor review.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
