# Generated by Django 4.2.30 on 2026-08-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="user",
        ),
        migrations.RemoveField(
            model_name="communitypost",
            name="author",
        ),
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userachievement",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="achievement",
        ),
        migrations.RemoveField(
            model_name="userachievement",
            name="user",
        ),
        migrations.DeleteModel(
            name="Achievement",
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.DeleteModel(
            name="CommunityPost",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="UserAchievement",
        ),
    ]
