# Generated by Django 4.2.30 on 2026-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_suspended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_mentor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                    ("MODERATOR", "Moderator"),
                    ("SUPPORT", "Support Agent"),
                    ("CONTENT_MANAGER", "Content Manager"),
                    ("ANALYTICS_MANAGER", "Analytics Manager"),
                    ("USER", "Standard User"),
                ],
                default="USER",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="suspension_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
