# Generated by Django 4.2.30 on 2026-08-16 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIMatchWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Production AI Matching Weights", max_length=100
                    ),
                ),
                (
                    "skill_overlap_weight",
                    models.IntegerField(
                        default=35, help_text="Weight for exact skill match (%)"
                    ),
                ),
                (
                    "wanted_offered_weight",
                    models.IntegerField(
                        default=25,
                        help_text="Weight for wanted/offered compatibility (%)",
                    ),
                ),
                (
                    "experience_weight",
                    models.IntegerField(
                        default=10, help_text="Weight for experience compatibility (%)"
                    ),
                ),
                (
                    "availability_weight",
                    models.IntegerField(
                        default=10, help_text="Weight for availability overlap (%)"
                    ),
                ),
                (
                    "learning_mode_weight",
                    models.IntegerField(
                        default=5, help_text="Weight for learning mode preference (%)"
                    ),
                ),
                (
                    "language_weight",
                    models.IntegerField(
                        default=5, help_text="Weight for language preference (%)"
                    ),
                ),
                (
                    "rating_weight",
                    models.IntegerField(
                        default=5, help_text="Weight for reputation rating (%)"
                    ),
                ),
                (
                    "activity_weight",
                    models.IntegerField(
                        default=5, help_text="Weight for active platform engagement (%)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=85)),
                ("reasons_json", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_matches_as_mentor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_matches_as_learner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
                "unique_together": {("user", "mentor")},
            },
        ),
    ]
