# Generated by Django 4.2.30 on 2026-08-15 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="availability",
            field=models.CharField(
                blank=True, default="Flexible Schedule", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="learning_mode",
            field=models.CharField(
                blank=True, default="1-on-1 Video Session", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="tags",
            field=models.CharField(
                blank=True, default="Peer Learning, Practical", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SkillReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=5)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="skills.skill",
                    ),
                ),
            ],
        ),
    ]
