# Generated by Django 4.2.30 on 2026-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_skill_availability_skill_featured_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, default="Explore top skills in this category."
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="seo_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="slug",
            field=models.SlugField(blank=True, max_length=220),
        ),
    ]
